version: '3.1'

services:
  api:
    build: .
    container_name: exaltic-api
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/exaltic_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root1234  
    working_dir: /opt/app
    depends_on:
      - db

  db:
    image: mysql
    container_name: exaltic-db
    volumes:
      - /data/db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=exaltic_db
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root1234
    ports:
      - 3306:3306
